# Generated by Django 3.2.12 on 2022-07-16 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APPS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_trans', models.CharField(max_length=100)),
                ('user_id_trans', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'table_transisi',
            },
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
