# Generated by Django 3.2.12 on 2022-07-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominggoodsitems',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
