# Generated by Django 3.2.12 on 2022-07-21 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('APPS', '0004_incominggoodsitems_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominggoodsitems',
            name='group_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
