# Generated by Django 3.2.12 on 2022-07-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0005_incominggoodsitems_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominggoods',
            name='typePayment',
            field=models.TextField(default='kartu_stock'),
        ),
    ]
