# Generated by Django 3.2.12 on 2022-07-23 01:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('APPS', '0007_alter_incominggoodsitems_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='outletProudct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('tendered_amount', models.FloatField(default=0)),
                ('amount_change', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('discount', models.FloatField(default=0)),
                ('typePayment', models.TextField(default='kartu_stock')),
            ],
        ),
        migrations.CreateModel(
            name='outletProudctItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('incomingGoods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPS.outletproudct')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPS.products')),
            ],
        ),
    ]
