# Generated by Django 3.2.12 on 2022-07-23 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0008_outletproudct_outletproudctitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominggoodsitems',
            name='outletProduct_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPS.outletproudct'),
        ),
    ]
