# Generated by Django 3.2.12 on 2022-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0009_incominggoodsitems_outletproduct_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incominggoods',
            name='typePayment',
        ),
        migrations.AddField(
            model_name='incominggoodsitems',
            name='statusPayment',
            field=models.TextField(default='Belum'),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
