# Generated by Django 3.2.12 on 2022-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0010_auto_20220723_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='nameCustomer',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='sales',
            name='phoneCustomer',
            field=models.TextField(default='-'),
        ),
    ]
