# Generated by Django 3.2.12 on 2022-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0011_auto_20220723_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='npwp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='ppn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='statusPPN',
            field=models.TextField(default='Tidak'),
        ),
    ]
