# Generated by Django 3.2.12 on 2022-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0012_auto_20220725_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='statusRetur',
            field=models.TextField(null=True),
        ),
    ]
