# Generated by Django 3.2.12 on 2022-08-03 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0013_sales_statusretur'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='incomingGoodsItems_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPS.incominggoodsitems'),
        ),
    ]
