# Generated by Django 3.2.12 on 2022-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0016_auto_20220926_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date_invoice',
            field=models.DateTimeField(null=True),
        ),
    ]
