# Generated by Django 3.2.12 on 2022-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0017_sales_date_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletproudct',
            name='date_invoice',
            field=models.DateTimeField(null=True),
        ),
    ]
