# Generated by Django 3.2.12 on 2022-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0018_outletproudct_date_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='typePayment',
            field=models.TextField(null=True),
        ),
    ]
