# Generated by Django 3.2.12 on 2022-10-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0019_sales_typepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletproudctitem',
            name='outletProduct_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPS.outletproudct'),
        ),
        migrations.AlterField(
            model_name='outletproudctitem',
            name='incomingGoods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPS.incominggoods'),
        ),
    ]
