# Generated by Django 3.2.12 on 2022-10-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPS', '0020_auto_20221015_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletproudctitem',
            name='incomingGoods_id',
        ),
        migrations.AddField(
            model_name='outletproudctitem',
            name='incomingGoodsItems_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APPS.incominggoodsitems'),
        ),
    ]
